version: "3"
services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html/

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html/

  nginx:
    image: nginx:alpine
    depends_on:
      - php-fpm
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
    depends_on:
      - php-fpm
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    hostname: postgres

  pgadmin:
    image: dpage/pgadmin4:5.0
    ports:
      - 8000:80
    volumes:
      - ${DATA_PATH_HOST}/pgadmin_volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    depends_on:
      - postgres

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
